import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { categorias, formatoCLP, productos } from '../data/productos';
import { useCart } from '../context/CartContext';
import ProductCard from '../components/ProductCard';

export function Home() { return <main><section className="hero container"><div className="hero-copy"><span className="eyebrow">Frescura que se nota</span><h1>Del campo a tu mesa, <em>con cariño.</em></h1><p>Productos frescos, naturales y de origen local para alimentar los momentos que importan.</p><Link to="/productos" className="btn btn-primary">Explorar productos <span>→</span></Link></div><div className="hero-art"><div className="hero-circle"><img src="/assets/img/manzanas-fuji.jpg" alt="Manzanas frescas" /></div><div className="floating-card"><strong>100%</strong><span>fresco y local</span></div></div></section><section className="values container"><div><span>01</span><h3>Directo del campo</h3><p>Trabajamos con productores locales para que recibas lo mejor.</p></div><div><span>02</span><h3>Calidad natural</h3><p>Seleccionamos cada producto con cuidado y compromiso.</p></div><div><span>03</span><h3>Para tu hogar</h3><p>Tu compra llega con la frescura y el sabor que mereces.</p></div></section></main>; }

export function Productos() { const [filtro, setFiltro] = useState('todos'); const visibles = filtro === 'todos' ? productos : productos.filter((p) => p.categoria === filtro); return <main className="catalog-page container"><div className="section-heading"><div><span className="eyebrow">Nuestra selección</span><h1>Productos frescos</h1></div><p>Explora nuestra variedad de productos frescos y naturales para tu hogar.</p></div><div className="filters">{categorias.map((cat) => <button key={cat.value} className={filtro === cat.value ? 'filter active' : 'filter'} onClick={() => setFiltro(cat.value)}>{cat.label}</button>)}</div><div className="products-grid">{visibles.map((producto) => <ProductCard key={producto.codigo} producto={producto} />)}</div></main>; }

export function Carrito() { const { items, total, cambiarCantidad, eliminar } = useCart(); const navigate = useNavigate(); const confirmar = () => { if (!items.length) return; alert('¡Gracias por tu compra! Esta demo no procesa pagos reales.'); navigate('/'); }; return <main className="cart-page container"><div className="section-heading"><div><span className="eyebrow">Tu selección</span><h1>Mi carrito</h1></div><p>{items.length ? `${items.length} producto(s) seleccionado(s)` : 'Aún no has agregado productos.'}</p></div>{!items.length ? <div className="empty-state"><div className="empty-icon">＋</div><h2>Tu carrito está vacío</h2><p>Agrega productos frescos para comenzar tu compra.</p><Link to="/productos" className="btn btn-primary">Ver productos</Link></div> : <div className="cart-layout"><div className="cart-items">{items.map(({ producto, cantidad }) => <article className="cart-item" key={producto.codigo}><img src={producto.img} alt={producto.nombre} /><div className="cart-item-info"><span className="product-category">{producto.categoria}</span><h2>{producto.nombre}</h2><p>{formatoCLP(producto.precio)} por {producto.unidad}</p><div className="quantity"><button onClick={() => cambiarCantidad(producto.codigo, -1)} aria-label="Disminuir">−</button><strong>{cantidad}</strong><button onClick={() => cambiarCantidad(producto.codigo, 1)} aria-label="Aumentar">+</button></div></div><div className="cart-item-side"><strong>{formatoCLP(producto.precio * cantidad)}</strong><button className="remove" onClick={() => eliminar(producto.codigo)}>Eliminar</button></div></article>)}</div><aside className="order-summary"><span className="eyebrow">Resumen</span><h2>Resumen de compra</h2><div className="summary-line"><span>Subtotal</span><strong>{formatoCLP(total)}</strong></div><div className="summary-line"><span>Despacho</span><span className="free">Gratis</span></div><div className="summary-total"><span>Total</span><strong>{formatoCLP(total)}</strong></div><button className="btn btn-primary btn-full" onClick={confirmar}>Confirmar compra</button></aside></div>}</main>; }

export function Nosotros() { return <main className="about-page container"><section className="about-hero"><div><span className="eyebrow">Nuestra historia</span><h1>Creemos en una forma más <em>natural</em> de vivir.</h1><p>HuertoHogar nació con una idea simple: acercar los sabores del campo a las familias, apoyando a productores locales y cuidando cada etapa del camino.</p></div><img src="/assets/img/zanahorias.jpg" alt="Cosecha de zanahorias" /></section><section className="about-grid"><div><span className="big-number">7+</span><p>productos cultivados y seleccionados con dedicación.</p></div><div><span className="big-number">100%</span><p>compromiso con la frescura y el origen local.</p></div><div><span className="big-number">1</span><p>comunidad creciendo alrededor de una mesa.</p></div></section></main>; }

export function Login() { const [email, setEmail] = useState(''); const navigate = useNavigate(); const submit = (e) => { e.preventDefault(); localStorage.setItem('usuario', JSON.stringify({ email })); navigate('/perfil'); }; return <AuthLayout title="Qué bueno verte" subtitle="Ingresa a tu cuenta para continuar."><form onSubmit={submit} className="auth-form"><label>Correo electrónico<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="tu@correo.com" /></label><label>Contraseña<input type="password" required minLength="4" placeholder="••••••••" /></label><button className="btn btn-primary btn-full">Iniciar sesión</button><p className="auth-switch">¿No tienes cuenta? <Link to="/registro">Regístrate aquí</Link></p></form></AuthLayout>; }
export function Registro() { const [nombre, setNombre] = useState(''); const [email, setEmail] = useState(''); const navigate = useNavigate(); const submit = (e) => { e.preventDefault(); localStorage.setItem('usuario', JSON.stringify({ nombre, email })); navigate('/perfil'); }; return <AuthLayout title="Bienvenido a casa" subtitle="Crea tu cuenta y disfruta de lo mejor del campo."><form onSubmit={submit} className="auth-form"><label>Nombre completo<input required value={nombre} onChange={(e) => setNombre(e.target.value)} placeholder="Tu nombre" /></label><label>Correo electrónico<input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="tu@correo.com" /></label><label>Contraseña<input type="password" required minLength="4" placeholder="Crea una contraseña" /></label><button className="btn btn-primary btn-full">Crear mi cuenta</button><p className="auth-switch">¿Ya tienes cuenta? <Link to="/login">Inicia sesión</Link></p></form></AuthLayout>; }
function AuthLayout({ title, subtitle, children }) { return <main className="auth-page container"><div className="auth-card"><div className="auth-brand"><span className="eyebrow">HuertoHogar</span><h1>{title}</h1><p>{subtitle}</p></div>{children}</div></main>; }
export function Perfil() { let usuario = {}; try { usuario = JSON.parse(localStorage.getItem('usuario')) || {}; } catch {} return <main className="profile-page container"><div className="profile-card"><div className="avatar">{(usuario.nombre || usuario.email || 'H').charAt(0).toUpperCase()}</div><span className="eyebrow">Mi cuenta</span><h1>{usuario.nombre || 'Tu perfil'}</h1><p>{usuario.email || 'Inicia sesión para ver tus datos.'}</p>{usuario.email ? <Link className="btn btn-secondary" to="/productos">Seguir comprando</Link> : <Link className="btn btn-primary" to="/login">Iniciar sesión</Link>}</div></main>; }
